### ISSUE TITLE
Background transparency

### ISSUE THREAD

**Issue by cassio-tav** [woheller69/omweather#30] opened 2023-05-06 18:20 UTC
**Feature request**

A transparent background will allow for better integration of the widget into the user's home screen, and thus improve user experience.

**Environment**
 - App version: v1.5
 - Android version: MIUI 14.0.1
 - Device: Xiaomi Mi 11T Pro
 - Home app: Kiss Launcher v. 3.20.0

**Comment by woheller69** [comment] 2023-05-06 18:26
duplicate of #29

**Closed by woheller69** 2023-05-06 18:26 UTC
Labels: bug
