### ISSUE TITLE
App says "no internet connection"

### ISSUE THREAD

**Issue by gregory441** [woheller69/omweather#27] opened 2023-04-17 13:31 UTC
**Describe the bug**
App does not show any weather data but keeps saying "no internet connection".

**How to Reproduce**
1. Opening up omWeather App
2. clicking on "Weather" in the Menu (shows a blank screen)
3. Clicking refresh-Button on the top (results in "no internet connection" message within in the app)

All other apps on the device do have internet connection without any issues. RainRadar in the same app works fine.

Interesting: Tried RadarWeather, which also is not able to load any weather data except the RainRadar. Error message is different: "Error loading weather data. Please try again later." (free translation from German)

**Expected behavior**
App might show weather data when I click on "weather".

**Screenshots**
No.

**Environment (please complete the following information):**
 - 1.4
 - Android 8.1
 - GS185

**Comment by woheller69** [comment] 2023-04-17 13:38
probably an issue with your VPN or firewall 
Duplicate of #19

**Closed by woheller69** 2023-04-17 13:38 UTC

**Comment by woheller69** [comment] 2023-04-20 07:26
Can you please try this? I am trying a different way to find if a device is online.
This problem sometimes also happens in my weather apps for some users.
So maybe this is a solution:

Remove .zip from filename and install.
[app-release.apk.zip](https://github.com/woheller69/omweather/files/11283517/app-release.apk.zip)

**Comment by woheller69** [comment] 2023-04-20 08:36
another small change.
[app-release.apk.zip](https://github.com/woheller69/omweather/files/11284138/app-release.apk.zip)
