### ISSUE TITLE
Additional Widget Option (Enhancement Request)

### ISSUE THREAD

**Issue by user10072023github** [woheller69/omweather#80] opened 2024-05-17 22:19 UTC
Hi wohellar69,
Thanks so much for the great app, its really valuable to have such quality info at my fingertips when running Android.  Only open source and trustworthy code fits my threat model so I really appreciate your efforts.  I just installed it today and am really impressed with it already.

Unsure if you're open to enhancement requests...feel free to ignore if you aren't.  Would you be interested in making an additional option for widgets that can be placed on the home screen?  Specifically, the same designs as what choices are already there except all with transparent backgrounds?  I like my widgets to be subtle and very toned down as I only want to glance at them when I know I need the info the widget is offering.

Thanks for considering,
R

P.S. Do you have a Kofi link?

**Comment by woheller69** [comment] 2024-05-22 06:18
Duplicate of #29, #30

**Closed by woheller69** 2024-05-22 06:18 UTC
Labels: bug
