### ISSUE TITLE
[Feature Request] Add a transparency feature\adjusting to a widget

### ISSUE THREAD

**Issue by hamsterrrr** [woheller69/omweather#75] opened 2024-01-09 19:40 UTC
**Describe the bug**
The semi-opaque widget steals some useful part of a display

**How to Reproduce**
Just add a widget to the screen
**Expected behavior**
Would be nice to see only data\icons
You could see how it's done in OmniRom Omnijaws Weather 
now the repo is archived , there is a [fork](https://github.com/vladrevers/OmniJaws) but looks suspicious due to probablef virus detected in [apk](https://github.com/vladrevers/OmniJaws/issues/4)
[VirusTotal](https://www.virustotal.com/gui/file/95b55d6d0f270388d8317058c244099a26dc4f64dcb124fbf32881662eb8b078)

**Comment by woheller69** [comment] 2024-01-09 19:44
duplicate of #29 and #30

**Closed by woheller69** 2024-01-09 19:44 UTC
